# Generated by Django 6.1.1 on 2026-10-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_updated_at_to_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(blank=True, help_text='Detailed investigation notes. Supports plain text.'),
        ),
    ]
